name: 'Setup Python Environment'
description: 'Set up Python and uv for the project'

inputs:
  python-version:
    description: 'Python version to use (optional, defaults to .python-version file)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.11"
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        cache-suffix: "-py${{ matrix.python-version }}"  # Separate cache per Python version
    
    # Just ensure the Python version is available
    - name: Install Python version
      if: ${{ inputs.python-version != '' }}
      shell: bash
      run: uv python install ${{ inputs.python-version }}