name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.11"
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        python-version: ${{ matrix.python-version }}
    
    - name: Install the project and dependencies
      run: |
        uv sync --locked --all-extras --dev
        uv add pylint --dev
    
    - name: Analysing the code with pylint
      run: |
        uv run pylint --rcfile=.pylintrc $(git ls-files 'src/torchrdit/*.py')