name: Deploy to Wiki

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.11"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: "3.10"
      
      - name: Install the project and dependencies
        run: |
          uv sync --locked --all-extras --dev
      
      - name: Generate documentation
        run: |
          mkdir -p wiki
          # Set PYTHONPATH to help pydoc-markdown find the module
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python -c "import sys; print('Python path:', sys.path)"
          python -c "import sys, os; print('Working directory:', os.getcwd())" || echo "getcwd failed"
          python -c "import os; print(os.listdir('.'))" || echo "listdir failed"
          # Try to import the module to verify it's available
          uv run python -c "import torchrdit; print('torchrdit version:', getattr(torchrdit, '__version__', 'unknown'))" || echo "Import torchrdit failed"
          # Run the documentation generator
          uv run python generate_docs.py
      
      - name: Deploy to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        env:
          WIKI_DIR: wiki/
          GH_MAIL: ${{ github.actor }}@users.noreply.github.com
          GH_NAME: ${{ github.actor }}